spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie_app_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "maharjan.works@gmail.com"
    password: "ovzu sopy gint pptb"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

project:
  poster: posters/

base:
  url: "http://localhost:8080"
